feat: account - Redefining some routes
vivesvoies/court-message pull request #117
Opened 2024-02-14 11:51 UTC by alallema

## General

Fixes #116

## Description

- remove`Administration` from menu or replace by `Équipe`
-

2024-02-14 13:42 UTC, louije requested changes
Je trouve ça cool !

J'ajouterais des tests sur `UsersController` pour s'assurer que les accès sont bien verrouillés.

2024-02-14 13:42 UTC, louije commented on app/models/ability.rb
> +    can :update, User, [ :name, :email ], id: user.id
le [:name, :email], il est mobilisé où ? J'ai pas l'impression que pour l'instant on vérifie précisément ce que tu as le droit de :read ou de :update, je me trompe ?

2024-02-14 13:42 UTC, louije commented on app/models/ability.rb
> +    can :read, User, [ :name, :email, :created_at ]
Pourquoi pas `belongs_to_team` là ? Sans ça quelqu’un qui a l'url court-message/equipe-ou-je-suis-pas/users risque pas d'avoir accès à la liste des gens ?

2024-02-14 14:32 UTC, alallema commented on app/models/ability.rb
> +    can :read, User, [ :name, :email, :created_at ]
C'est ce que j'avais fait au début mais j'avais des soucis pour je ne sais plus quoi.
Du coup j'ai mis un sélecteur de champs. Mais tu as raison je vais le rajouter

2024-02-14 14:38 UTC, alallema commented on app/models/ability.rb
> +    can :update, User, [ :name, :email ], id: user.id
Non en effet je me suis demandé si ça pouvait être bien de la rajouter pour éviter que les gens ai accès aux rôles. Mais en réalité on s'en sert pas pour l'instant. Je peux clairement l'enlever

2024-02-14 14:40 UTC, alallema commented
@louije 
> J'ajouterais des tests sur UsersController pour s'assurer que les accès sont bien verrouillés.

Oui d'ailleurs si tu as le temps de regarder vite fait la PR de tests comme ça je la merge 😄 
Sauf si t'as pas le temps ça ajoute juste les tests à la CI

2024-02-14 16:06 UTC, alallema commented on test/controllers/users_controller_test.rb
> +  # test "should not allow user to update via UserController" do
J'ai commenter tous ces tests en attendant de refaire le `UsersController`

2024-02-14 17:43 UTC, alallema commented on app/models/ability.rb
> +    can :read, User, [ :name, :email, :created_at ]
Alors j'ai retrouvé pourquoi j'avais pas mis `belongs_to_team` je sais pas pourquoi mais après j'ai plus accès aux vues en questions c'est ce qui fait planté les tests [ici](https://github.com/vivesvoies/court-message/pull/117/checks#step:6:239)

Et j'ai cette erreur:
```
I, [2024-02-14T18:40:56.811690 #88513]  INFO -- : Started GET "/teams/userteam/users/3" for ::1 at 2024-02-14 18:40:56 +0100
I, [2024-02-14T18:40:56.835388 #88513]  INFO -- : Processing by UsersController#show as HTML
I, [2024-02-14T18:40:56.835472 #88513]  INFO -- :   Parameters: {"team_id"=>"userteam", "id"=>"3"}
I, [2024-02-14T18:40:56.846979 #88513]  INFO -- : Completed 500 Internal Server Error in 11ms (ActiveRecord: 2.2ms | Allocations: 3443)


F, [2024-02-14T18:40:56.855807 #88513] FATAL -- : 
NoMethodError - undefined method `team' for an instance of User:

I, [2024-02-14T18:40:56.875556 #88513]  INFO -- : Finished "/cable" [WebSocket] for ::1 at 2024-02-14 18:40:56 +0100
I, [2024-02-14T18:40:56.875777 #88513]  INFO -- : Hotwire::Livereload::ReloadChannel stopped streaming from hotwire-reload
I, [2024-02-14T18:40:56.912284 #88513]  INFO -- : Started POST "/__better_errors/3f2a53eefeb64393/variables" for ::1 at 2024-02-14 18:40:56 +0100
```

2024-02-14 19:00 UTC, alallema commented on app/models/ability.rb
> +    can :read, User, [ :name, :email, :created_at ]
J'ai tout de même laissé le `belongs_to_team`, je verrais si ça pose problème par la suite

2024-02-14 19:04 UTC, louije commented on app/models/ability.rb
> +    can :read, User, [ :name, :email, :created_at ]
oui faut sans doute trouver une syntaxe qui marche mieux parce que presque tous les modèles ont une propriété `team` alors que `User` a une propriété `teams` ou `team_ids`. Chuis trop fatigué là pour l'inventer :D

2024-02-16 17:30 UTC, louije commented on app/controllers/users_controller.rb
> +  before_action :set_team, only: %i[ index show ]
s'assurer qu'on a ça pour les mêmes actions que :set_user sinon risque de sécu

2024-02-16 17:35 UTC, louije commented on app/models/ability.rb
> +    can [ :create, :update, :destroy ], User
attention, l'admin de l'équipe A semble pouvoir éditer quelqu’un de l'équipe B

2024-02-16 17:38 UTC, louije commented on config/routes.rb
> +    resources :users, only: [ :index, :show, :edit, :new, :update, :destroy ]
on n'a pas besoin de `:new` ni de `:show`
voire de `:destroy` pour le moment (c'est unspecified)

2024-02-16 17:38 UTC, louije approved these changes
nickel modulo s'assurer que c'est bien secure

2024-03-01 17:23 UTC, merged