Implement search for contact and create new conversation
vivesvoies/court-message pull request #191
Opened 2024-04-08 19:13 UTC by alallema

## Description

At the moment, the new conversation button opens a modal, but it should be possible to search in contacts to create a new conversation.

## Changes

- Add a search page for searching contacts
- Add a new conversation route

2024-04-09 20:35 UTC, louije requested changes
- du front-end (le `<li>` putain !)
- des règles de gestion (n'afficher les résultats que dans la team actuelle)
- du rails spécifique (pas utiliser `new` pour toucher à la base, pas désactiver turbo, etc.)

plein de petits et moyens trucs mais sinon c'est top

2024-04-09 20:35 UTC, louije commented on app/controllers/conversations_controller.rb
> +      redirect_to team_conversation_path(@team, contact.conversation), notice: I18n.t(".conversations.create.success")
bizarre / wrong de toucher la base dans un `new`. New, ça affiche un formulaire pour créer un truc. Là il faut que tu fasses un lien vers la route `create` / POST. Ça veut dire `link_to "truc", conversations_path, method: :post, etc`

2024-04-09 20:35 UTC, louije commented on app/controllers/messages_controller.rb
> +    end
yes mais pourquoi charger le formulaire si on ne peut pas poster alors ?

2024-04-09 20:35 UTC, louije commented on app/javascript/controllers/search_form_controller.js
> +  search() {
mérite limite de s'appeler `debounceSubmit` parce que c'est pas vraiment un `search` non ?

2024-04-09 20:35 UTC, louije commented on app/models/ability.rb
> +    can [ :create, :read, :update ], Conversation, belongs_to_team
c'est utilisé où, le update?

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +              class: "inline-form" do |form| %>
no such class

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +          <%= form.search_field :query, class: "ContactSearch__form form-control", placeholder: "Search", data: { action: "input->search-form#search" } %>
pareil pour `form-control`, no such class, sans doute un copier coller ?
placeholder à mettre à jour

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +    <%= turbo_frame_tag "contact_result" do %>
`contact_search_results`. En tout cas mettre results au pluriel.

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +      <ol id="contacts" class="ContactSearchList">
nope pour l'id. Pas impossible qu'on l'utilise ailleurs. vaut mieux être plus spécifique `"contact_results"`

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +        <li class="ContactSearchResults">
AAAAAAAAAAARGH

tu mets tous tes résultats dans un seul `<li>` au lieu de les mettre chacun dans leur `<li>`. 
`<li>` c'est List Item !

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +            <% @results&.each do |contact| %>
soit c'est `if present?` soit c'est `@results&.truc`, mais pas les deux non ?

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +              <div class="ContactSearchResults__name">
voilà ça devrait être ça ton `<li class="ContactSearchResult">`.

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +                <%= link_to contact.conversation.present? ? team_conversation_path(@team, contact.conversation.id) : new_team_conversation_path(@team, contact: contact.id), class: "ContactSearchResul
cf là haut - ça devrait pas être un lien vers new. new est pas fait pour ça. si tu touches la base ça devrait être une requête POST ou PATCH, en l'occurrence POST qui touche la route create.

Après gérer ça dans un link_to one-liner c'est difficile, donc tu pourrais faire un helper dans `TeamsHelper` pour simplifier, genre `link_to_or_create_conversation(contact)`

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +  </footer>
chais pas trop quoi faire de ça. est-ce que c'est la peine de le montrer si y'a pas de conversation sélectionnée ?

2024-04-09 20:35 UTC, louije commented on app/views/conversations/_conversation_detail.html.erb
> +      <% end %>
pour moi ça devait pas être éditable quand on est déjà dans une conversation.
je mettrais pas le link_to.

2024-04-09 20:35 UTC, louije commented on app/views/messages/new.html.erb
> +            :disabled => !@message %>
bah on n'est pas dans les années 2000 hein, tu peux écrire `disabled: !@message`

2024-04-09 20:35 UTC, louije commented on app/views/messages/new.html.erb
j'aime pas trop ce pattern de mettre tout le code en double au cas où on aurait un @message ou non. Pour moi si on n'a pas de @message, on n'a pas de formulaire.

2024-04-09 20:35 UTC, louije commented on config/routes.rb
> +    resources :conversations, only: [ :index, :show, :new ] do
meh

2024-04-09 20:35 UTC, louije commented on app/views/contacts/search.html.erb
> +                <%= link_to contact.conversation.present? ? team_conversation_path(@team, contact.conversation.id) : new_team_conversation_path(@team, contact: contact.id), class: "ContactSearchResul
AUSSI : `turbo: false`, c'est naze. Ce que tu veux, c'est `turbo_frame: :primary`.

2024-04-09 20:35 UTC, louije commented on test/controllers/messages_controller_test.rb
> +  # test "should not get new without a conversation_id" do
c'est ton `if params[:conversation_id]` dans `messages_controller.rb`. Normalement la route est censée échouer si y'a pas de `conversation_id`.

2024-04-09 20:48 UTC, alallema commented on app/views/contacts/search.html.erb
> +              class: "inline-form" do |form| %>
Si elle est a la fin de `_contact.scss` deso je me suis pas relue je devais tenter des trucs ... Je vais le renommée

2024-04-09 20:48 UTC, alallema commented on app/models/ability.rb
> +    can [ :create, :read, :update ], Conversation, belongs_to_team
Je suis pas sure mais sans j'ai une erreur cancancan ...

2024-04-09 20:50 UTC, alallema commented on app/controllers/conversations_controller.rb
> +      redirect_to team_conversation_path(@team, contact.conversation), notice: I18n.t(".conversations.create.success")
Ah mais oui c'est parce qu'au debut j'utilisais la route et la views `new` vue que ca dit nouvelle conversation mais j'ai fait des modifs

2024-04-09 20:51 UTC, alallema commented on app/controllers/contacts_controller.rb
> +    @contacts = Contact.all
J'étais tenté d'afficher tous les contacts quand tu cliquais dans la barre de recherche ... j'ai du abandonner l'idée mais le code est resté ... oopsy

2024-04-09 20:51 UTC, alallema commented on app/assets/stylesheets/components/_contacts.scss
> +  box-shadow: 0px 3px 4px var(--list-contact-result-shadow);
J'ai pas compris ...

2024-04-09 20:54 UTC, alallema commented on app/views/contacts/search.html.erb
> +        <li class="ContactSearchResults">
Deso. A la base ils etaient tous bien dans un `<li>` mais j'ai eu des soucis avec le bouton, je vais remedier a ca

2024-04-09 20:56 UTC, alallema commented on app/views/contacts/search.html.erb
> +  </footer>
Bah je sais pas non plus mais il y ai sur l'UI

2024-04-09 20:56 UTC, alallema commented on app/views/messages/new.html.erb
> +            :disabled => !@message %>
Merci

2024-04-09 20:57 UTC, alallema commented on app/views/messages/new.html.erb
> +            :disabled => !@message %>
Cela dit si on ne met pas le footer de message on peut l'enlever ...

2024-04-09 21:07 UTC, alallema commented on app/views/messages/new.html.erb
Je suis d'accord aussi j'ai enlevé cette partie. Pas de messages si pas de contact

2024-04-09 21:07 UTC, alallema commented on test/controllers/messages_controller_test.rb
> +  # test "should not get new without a conversation_id" do
J'ai enlever la modification des messages ☺️

2024-04-09 21:08 UTC, alallema commented on app/assets/stylesheets/components/_conversation_detail.scss
> +.ContactSearch__footer,
Element retiré ☺️

2024-04-09 21:55 UTC, alallema commented on app/assets/stylesheets/components/_conversation_detail.scss
>    font-weight: bold;
Elles marchent pas les `var(--font-body-bold)` je les ai mises mais c'est pas en gras du coup

2024-04-10 06:06 UTC, louije commented on app/assets/stylesheets/components/_conversation_detail.scss
>    font-weight: bold;
Oui faut pas les utiliser sur `font-weight:` mais sur `font:`.

2024-04-10 06:11 UTC, louije commented on app/assets/stylesheets/components/_contacts.scss
> +  box-shadow: 0px 3px 4px var(--list-contact-result-shadow);
On a déjà une série de variables qui s'appellent `--quelquechose-shadow` et elles sont au format `1px 1px 1px rgba(etc, etc, etc, etc)`, en gros, ce que tu mets dans un `box-shadow`.

Donc soit tu fais une variable `--list-contact-result-shadow: 0px 3px 4px var(--color-dark8)`, soit tu fais une variable `--list-contact-results-box: var(--color-dark8)`.

Mais j'aimais bien l'idée de standardiser les ombres – ça serait cool qu'on ait la même ombre pour le menu "nom de l'utilisateur" et pour celui-là, après tout, c'est censé être à la même "hauteur" sur l'écran.

2024-04-10 06:12 UTC, louije commented on app/controllers/contacts_controller.rb
> +    @contacts = Contact.all
alors ça serait obvs quelque chose comme `Contact.where(team: Current.team)`

2024-04-10 06:13 UTC, louije commented on app/models/ability.rb
> +    can [ :create, :read, :update ], Conversation, belongs_to_team
à quel endroit ?

2024-04-10 11:18 UTC, alallema commented on app/models/ability.rb
> +    can [ :create, :read, :update ], Conversation, belongs_to_team
Sur la search. Je vais faire des tests et trouver d'ou ca vient exactement

2024-04-10 11:34 UTC, alallema commented on app/assets/stylesheets/components/_contacts.scss
> +  box-shadow: 0px 3px 4px var(--list-contact-result-shadow);
J'ai compris ! J'ai utilisé la même que pour le menu mais je vois bien que l'UI c'est pas la même

2024-04-10 12:12 UTC, alallema commented on app/models/ability.rb
> +    can [ :create, :read, :update ], Conversation, belongs_to_team
C'est bon en fait y a plus d'erreur j'ai du modifier des trucs entre temps

2024-04-10 12:13 UTC, alallema commented on config/routes.rb
> +    resources :conversations, only: [ :index, :show, :new ] do
Je l'ai remplacé par create 😅

2024-04-10 12:14 UTC, alallema commented on app/controllers/contacts_controller.rb
> +                 Contact.where("name ILIKE :search", search: "%#{@search}%")
Je vais modifier cette method je pense que ca pourrait etre cool de cherche par mail ou numero de tel aussi non ?

2024-04-10 12:15 UTC, alallema commented on app/assets/stylesheets/components/_contacts.scss
> +  font-weight: var(--font-body-bold);
Pour info je l'ai remis comme il etait

2024-04-10 12:48 UTC, alallema commented on app/controllers/contacts_controller.rb
> +                 Contact.where("name ILIKE :search", search: "%#{@search}%")
Et moi j'aime bien le `le named parameter` meme si c'est overkill je trouve ca plus facile a lire surtout dans les query de recherche non ?

2024-04-11 16:23 UTC, merged